/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthsRegisterRouteImport } from './routes/auths/register'
import { Route as AuthsLoginRouteImport } from './routes/auths/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthsRegisterRoute = AuthsRegisterRouteImport.update({
  id: '/auths/register',
  path: '/auths/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthsLoginRoute = AuthsLoginRouteImport.update({
  id: '/auths/login',
  path: '/auths/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auths/login': typeof AuthsLoginRoute
  '/auths/register': typeof AuthsRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auths/login': typeof AuthsLoginRoute
  '/auths/register': typeof AuthsRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auths/login': typeof AuthsLoginRoute
  '/auths/register': typeof AuthsRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auths/login' | '/auths/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auths/login' | '/auths/register'
  id: '__root__' | '/' | '/auths/login' | '/auths/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthsLoginRoute: typeof AuthsLoginRoute
  AuthsRegisterRoute: typeof AuthsRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auths/register': {
      id: '/auths/register'
      path: '/auths/register'
      fullPath: '/auths/register'
      preLoaderRoute: typeof AuthsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auths/login': {
      id: '/auths/login'
      path: '/auths/login'
      fullPath: '/auths/login'
      preLoaderRoute: typeof AuthsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthsLoginRoute: AuthsLoginRoute,
  AuthsRegisterRoute: AuthsRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
