/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppJobSeekersIndexRouteImport } from './routes/_app/jobSeekers/index'
import { Route as AppEmployersIndexRouteImport } from './routes/_app/employers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/_auth/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobSeekersIndexRoute = AppJobSeekersIndexRouteImport.update({
  id: '/_app/jobSeekers/',
  path: '/jobSeekers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmployersIndexRoute = AppEmployersIndexRouteImport.update({
  id: '/_app/employers/',
  path: '/employers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/employers': typeof AppEmployersIndexRoute
  '/jobSeekers': typeof AppJobSeekersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/employers': typeof AppEmployersIndexRoute
  '/jobSeekers': typeof AppJobSeekersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_app/employers/': typeof AppEmployersIndexRoute
  '/_app/jobSeekers/': typeof AppJobSeekersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/employers'
    | '/jobSeekers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/employers'
    | '/jobSeekers'
  id:
    | '__root__'
    | '/'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/unauthorized'
    | '/_app/employers/'
    | '/_app/jobSeekers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AppEmployersIndexRoute: typeof AppEmployersIndexRoute
  AppJobSeekersIndexRoute: typeof AppJobSeekersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/jobSeekers/': {
      id: '/_app/jobSeekers/'
      path: '/jobSeekers'
      fullPath: '/jobSeekers'
      preLoaderRoute: typeof AppJobSeekersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/employers/': {
      id: '/_app/employers/'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof AppEmployersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AppEmployersIndexRoute: AppEmployersIndexRoute,
  AppJobSeekersIndexRoute: AppJobSeekersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
